"""create sales table

Revision ID: 4a870c17982d
Revises: 33680203b197
Create Date: 2026-08-07 18:28:36.293465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a870c17982d'
down_revision: Union[str, Sequence[str], None] = '33680203b197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('collection_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("collection_status IN ('COLLECTED', 'PENDING_COLLECTION')", name='ck_sale_collection_status'),
    sa.CheckConstraint("payment_status IN ('PAID', 'PARTIAL', 'UNPAID')", name='ck_sale_payment_status'),
    sa.CheckConstraint('amount_paid <= total_amount', name='ck_sale_amount_paid_not_greater_than_total'),
    sa.CheckConstraint('amount_paid >= 0', name='ck_sale_amount_paid_non_negative'),
    sa.CheckConstraint('discount >= 0', name='ck_sale_discount_non_negative'),
    sa.CheckConstraint('remaining_balance >= 0', name='ck_sale_remaining_balance_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sale_subtotal_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_sale_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
