"""make product name unique

Revision ID: a1b72707ba9e
Revises: 0b3130fcec6e
Create Date: 2026-08-21 23:04:04.174020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b72707ba9e'
down_revision: Union[str, Sequence[str], None] = '0b3130fcec6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("products_name_key","products",["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_name_key", "products", type_="unique")    
    # ### end Alembic commands ###
