services:
  postgres:
    image: postgres:17
    container_name: business_pulse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: business_pulse_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

    business-pulse:
      build: .
      container_name: business_pulse_app
      restart: unless-stopped
      ports:
        - "8501:8501"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        GEMINI_MODEL: ${GEMINI_MODEL}
      depends_on:
        - postgres

volumes:  
  postgres_data:
  ollama_data:
